### ISSUE TITLE
Package Uploads

### ISSUE THREAD

**Issue by divy-work** [nestdotland/api#13]
We have a really sweet GQL API and now it's time to implement package creation and twig interactions.

Here's a little TODO list:

#### Part 1

- [x] Use the graphql API to create a package entry in the database (after that package can be uploaded using the http endpoint)

#### Part 2

- [x] Create a multipart upload handler for actix
- [x] Store the tar file in a tmp directory (shared with twig)
- [x] Read apiKey, wallet content (for PSTs, optional), packageName from request body.
- [x] Authenticate with apiKey and confirm packageName in database
- [x] Create a transaction with twig.
- [x] Create a package-upload entry in the db with transaction details
- [x] Do a complete real-life test with `yolk` and fix errors (if any) 

#### Part 3
- [ ] Throw a little discord party _(oh well)_

(cc @jletey)

**Comment by tbaumer22** [comment]
I'll help with part 3.

**Comment by divy-work** [comment]
@t8 We'll need to complete the transaction route at twig to complete package uploads. 
@zorbyte had something to push I guess, I'll create a PR at twig for now.

**Comment by t8** [comment]
Good point @divy-work. Once we can get the transaction endpoint(s) set up, I can start implementing PSTs. Let me know what we need to do for both Rust and Twig API deployments.

**Comment by divy-work** [comment]
@t8 I got the transaction endpoint setup and they are tested with the API. I've also added a wallet key in the upload payload (which currently goes blank)

**Comment by divy-work** [comment]
We could now have a option with the publish command `--wallet ../the_wallet.json` and yolk will accept the wallet and take it to the API.

**Comment by t8** [comment]
Awesome work @divy-work! Let's discuss the final piece to this issue at our next meeting, where we can discuss when PST implementations will begin on my side of things.

**Comment by divy-work** [comment]
Completed testing everything. Merging the PR now. We can continue the PST discussion.

_Also, what about the discord party?_

**Comment by t8** [comment]
I didn't forget!
